#!/bin/zsh

system_type=$(uname -s)
downloads='dtmux curl'

# Hello
echo "Bootstrapping now..."

######### Download stuff ###########
# Check for npm
if command -v npm; then :
else
	if [ -n "$(uname -a | grep Debian)" ]
	then
		sudo apt-get -y install $downloads
	elif [ -n "$(uname -a | grep Arch)" ]
	then
		pacman -S $downloads
	else
		echo "You need to install npm\n"
		exit 1
	fi
fi

######### Vim Stuff ###########
# Install Vim-plug plugins
vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'

######### Tmux Stuff ###########
# DO NOT APT INSTALL NPM

# Update npm
# sudo npm install npm@latest -g

# Install stuff for tmux
# sudo npm install -g tmux-mem tmux-cpu

# Reload source for tmux
tmux source-file ~/.tmux.conf

######### Zsh Stuff ###########
# Check for oh my zsh/install
if [ -d ~/.oh-my-zsh ]; then
	echo "oh-my-zsh is already installed, skipping"
 else
 	echo "oh-my-zsh is not installed"
fi

# Check for fzf
if git clone --depth 1 https://github.com/junegunn/fzf.git ~/.config/fzf; then :
else
	cd ~/.config/fzf && git pull
fi
~/.config/fzf/install --all --key-bindings --completion --no-update-rc

# Check for zsh-autosuggestions
if git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/plugins/zsh-autosuggestions; then :
else
	cd ~/.oh-my-zsh/plugins/zsh-autosuggestions && git pull
fi

# Zsh syntax highlightin
if git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting; then :
else
	cd ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && git pull
fi

# Check for zsh-completions
if git clone --depth=1 https://github.com/zsh-users/zsh-completions ~/.oh-my-zsh/custom/plugins/zsh-completions; then :
else
	cd ~/.oh-my-zsh/custom/plugins/zsh-completions && git pull
fi

# Install pure-theme for zsh
mkdir -p "$HOME/.zsh"
git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh/pure"

# Source zshrc
source ~/.zshrc

# Set zsh to shell
chsh -s $(which zsh)

# Get bat??
if command -v bat; then :
else
	if [ -n "$(uname -a | grep Debian)" ]; then
	#	sudo apt install bat
		wget https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb
		sudo dpkg -i bat_0.12.1_amd64.deb
		rm bat_0.12.1_amd64.deb
	fi
	if [ "$system_type" = "Darwin" ]; then
		brew install bat
	fi
fi
